server:
  port: 8080

spring:
  application:
    name: gateway-service

dgs:
  graphql:
    graphiql:
      enabled: true
      path: /graphiql

subgraphs:
  users:
    url: http://users-service:8081/graphql
  loans:
    url: http://loans-service:8082/graphql