spring:
  application:
    name: users-service

server:
  port: 8081

dgs:
  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql

logging:
  level:
    com.neobank.users: DEBUG
    com.netflix.graphql.dgs: DEBUG
